openapi: 3.0.0
info:
  title: E-commerce APIs
  description: Documentation for all backend apis
  version: 1.0.0
components:
  securitySchemes:
    jwt:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    error:
      type: object
      properties:
        message:
          type: string
        status:
          type: number      
security:
  - jwt: []
paths:
  /products:
    get:
      summary: Get all products
      tags: 
       - Products
      responses:
        200:
          description: Products fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    size:
                      type: number
                    name:
                      type: string
                    description:
                      type: string
                    category:
                      type: string
                    image:
                      type: string
                    price:
                      type: number
              example:
                - size: 10
                  name: shirt
                  description: description for shirt
                  category: pants
                  image: url
                  price: 15      
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: Internal server error
                status: 500       
        404:
          description: Cannot find products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: not found
                status: 404
    post:
      summary: Add product
      tags: 
       - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                size:
                  type: number
                  example: 12
                name:
                  type: string
                  example: any
                description:
                  type: string
                  example: description
                price:
                  type: number
                  example: 122
                category:
                  type: string
                  example: T-Short
                image:
                  type: string
                  example: ass
      responses:
        200:
          description: Products fetched successfully
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: Internal server error
                status: 500       
        404:
          description: Cannot find products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: not found
                status: 404
  /products/{id}:
    get:
      summary: Get product by ID
      tags: 
      - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the product to retrieve
      responses:
        200:
          description: Product fetched successfully
          content:
            application/json:
              schema:
                type: object
                  properties:
                    size:
                      type: number
                    name:
                      type: string
                    description:
                      type: string
                    category:
                      type: string
                    image:
                      type: string
                    price:
                      type: number
              example:
                - size: 10
                  name: shirt
                  description: description for shirt
                  category: pants
                  image: url
                  price: 15      
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: Internal server error
                status: 500       
        404:
          description: Cannot find product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: not found
                status: 404
  /products/{id}:
    post:
      summary: update product by ID
      tags: 
      - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the product to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                size:
                  type: number
                  example: 12
                name:
                  type: string
                  example: any
                description:
                  type: string
                  example: description
                price:
                  type: number
                  example: 122
                category:
                  type: string
                  example: T-Shirt
                image:
                  type: string
                  example: ass
      responses:
        200:
          description: Product updated successfully
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: Internal server error
                status: 500       
        404:
          description: Cannot find product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: not found
                status: 404
  
  /accounts/signup:
    post:
      tags:
        - Account
      description: Register user
      requestBody: 
        required: true
        content:
         application/json:
          schema:
            type: object
            properties:
              userName:
                type: string
                example: Imad.Saad 
              firstName:
                type: string
                example: Imad 
              lastName:
                type: string
                example: saad 
              password:
                type: string
                example: Password@123 
      responses:
        201:
          description: User added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: h1g23jhg12g3
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: Internal server error
                status: 500       
        404:
          description: Cannot find products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: not found
                status: 404
        400:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: Bad Request
                status: 400
  /accounts/signin:
    post:
      tags:
        - Account
      description: Sign in to the platform
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  example: Imad.saad
                password:
                  type: string
                  example: Password@123
      responses:
        200:
          description: Sign in successfully
          content:
            application/json:
               schema:
                type: object
                properties:
                  token:
                    type: string
                    example: h1g23jhg12g3
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: Internal server error
                status: 500       
        404:
          description: Cannot find products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: not found
                status: 404
        400:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: Bad Request
                status: 400            



