openapi: 3.0.0
info:
  title: E-commerce APIs
  description: Documentation for all backend apis
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get all products
      tags: 
       - Products
      responses:
        200:
          description: Products fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    size:
                      type: number
                    name:
                      type: string
                    description:
                      type: string
                    category:
                      type: string
                    image:
                      type: string
                    price:
                      type: number
              example:
                - size: 10
                  name: shirt
                  description: description for shirt
                  category: pants
                  image: url
                  price: 15      
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: Internal server error
                status: 500       
        404:
          description: Cannot find products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: not found
                status: 404
    post:
      summary: Add product
      tags: 
       - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                size:
                  type: number
                  example: 12
                name:
                  type: string
                  example: any
                description:
                  type: string
                  example: description
                price:
                  type: number
                  example: 122
                category:
                  type: string
                  example: T-Short
                image:
                  type: string
                  example: ass
      responses:
        200:
          description: Products fetched successfully
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: Internal server error
                status: 500       
        404:
          description: Cannot find products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: not found
                status: 404
  /products/{id}:
    get:
      summary: Get product by ID
      tags: 
      - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the product to retrieve
      responses:
        200:
          description: Product fetched successfully
          content:
            application/json:
              schema:
                type: object
                  properties:
                    size:
                      type: number
                    name:
                      type: string
                    description:
                      type: string
                    category:
                      type: string
                    image:
                      type: string
                    price:
                      type: number
              example:
                - size: 10
                  name: shirt
                  description: description for shirt
                  category: pants
                  image: url
                  price: 15      
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: Internal server error
                status: 500       
        404:
          description: Cannot find product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                message: not found
                status: 404
components:
  schemas:
    error:
      type: object
      properties:
        message:
          type: string
        status:
          type: number  


